<a href="https://colab.research.google.com/github/nureeee/DeepLearning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow
 * 계산할 내용들을 미리 정리를 해 놓고 실제 계산이 필요한 순간(훈련)에 데이터(배열)을 흘려 보낸다.

* 파이썬 환경에 텐서플로우라는 세션을 따로 만든 것??
* 텐서플로우 세센 안에 모델을 만듬?
* 안에 평가 방식, 옵션 지표들을 설정해 준다.
* 텐서플로우 안의 모델이 그래프이다.

**Tensorflow 기본사용방법**

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# Tensor 만들기

tf.constant()
 * list -> Tensor

In [3]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

* tuple -> Tensor

In [4]:
tf.constant(((1, 2, 3),
            (4, 5, 6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

텐서플로우에 넘파이 배열을 넣어도 잘 된다.

* ndarray -> Tensor

In [5]:
arr = np.array([1, 2, 3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보확인

In [6]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**shape**확인하기

In [7]:
tensor.shape # 넘파이와 똑같이 확인

TensorShape([3])

**dtype** 확인하기

In [8]:
tensor.dtype

tf.int32

Tensor를 생성하면서 dtype 정의해 주기

In [9]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [10]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

tensor dtype 변환하기
* numpy 에서는 astype
* tensorflow 에서는 cast사용

In [12]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [13]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [14]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

# Tensorflow 난수 생성

* numpy에서 정규 분포 : np.random.randn
* tensorflow 에서는 정규분포 : tf.random.nomal

In [15]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.31860247, -0.84452426, -1.1078489 ],
       [ 0.2993421 ,  0.93404776,  0.39097193],
       [-0.26325005,  1.1937352 ,  0.2610934 ]], dtype=float32)>

In [16]:
# 균등분포
tf.random.uniform([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5874375 , 0.25248134, 0.32919526],
       [0.17729414, 0.33525085, 0.7418909 ],
       [0.22209477, 0.54085696, 0.14098144]], dtype=float32)>

In [17]:
# tensorflow 배열은 수정 불가!
# 반드시 tensorflow의 session의 variable만 수정 가능
tensor[0] = 1 # 불가능!!

TypeError: ignored

# keras로 MNIST 분류 모델링 수행하기

## MNIST 손글씨 데이터 세트 불러오기

In [19]:
import tensorflow as tf
from tensorflow.keras import datasets

In [20]:
mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [21]:
X_train.shape, y_train.shape

((60000, 28, 28), (60000,))

**Fully Connected Layer**를 사용하기 위해 평탄화, 필요에 따라 OHE을 진행

# Keras란?
* tensorflow를 기반으로 하는 유명한 논문, 레이어들을 구현을 해 놓은 패키지

# Fully Connected layer 모델링 하기
* 레이어들은 tf.keras.layers 패키지에 모두 들어 있음
* Flatten Layer : 배치를 제외한 평탄화 담당
* Dense Layer : Affine 연산을 담당
* Activation Layer : 활성화 함수 레이어 (선택에 따라서 사용을 안할 수도 있다.)


In [22]:
X_train = X_train /255.0
X_test = X_test / 255.0

In [30]:
from tensorflow.keras.layers import Dense, Flatten, Activation, Input

# 입력층
input = Input(shape=(28, 28)) 
net = Flatten()(input) # 평탄화가 된 내용 저장됨

# Flatten은 클래스의 형식이지만 함수처럼 사용??
# net은 객체??
#은닉층
net = Dense(512)(net) # 512개의 뉴러느이 가진 텐서
net = Activation('relu')(net)

net = Dense(256)(net)
net = Activation('relu')(net)

# 출력층
net = Dense(10)(net)
net = Activation('softmax')(net)

# 모델 생성 - 계산 그래프가 세션 내에 생성된다.
model = tf.keras.Model(inputs=input, outputs=net, name='BASIC_MNIST' )
model.summary() # 모델 요약

Model: "BASIC_MNIST"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 28, 28)]          0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 512)               401920    
_________________________________________________________________
activation_3 (Activation)    (None, 512)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 256)               131328    
_________________________________________________________________
activation_4 (Activation)    (None, 256)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                

# 최적화 계획 세우기
* Loss Function(손실함수) - MSe, CEE를 쓸지를 결정
* Optimization (최적화 함수) - SGD, ADAM, RMsprop을 쓸지를 결정
* Metrics - 테스트 세트에 대한 평가 기준

## Loss Function 선정 기준
**외우기**
* 이진 분류를 수행하는 경우 ( Binary Classification )
  * mse : 출력층의 뉴런이 1개인 경우 - with sigmoid
  * cross entropy error : 출력층의 뉴런이 2개인 경우  with softmax (제일 자주 사용되는 방법)
   * binary_crossentropy를 사용하면 된다.
* 다중 분류를 수행하는 경우 (Multiclass Classification)
  * cross entropy error : 출력층의 뉴런을 클래스의 개수만큼 설정
   * categorical_crossentropy를 사용하면 된다.


## Categorical Cross Entropy의 종류
* Label이 [0, 1, 2] 처럼 원핫인코딩이 되어있지 않은 경우
 * sparse_categorical_crossentropy를 사용
* Label이 원핫인코딩이 되어있는 경우
 * categorical_crossentropy를 사용

**y_train**을 확인해서 어떤 Loss Function을 사용할 지 결정해 보자


In [31]:
y_train.shape

(60000,)

In [32]:
y_train[:3]

array([5, 0, 4], dtype=uint8)

y_train 확인결과 원핫인코딩이 되어있지 않음
sparse_categorical_crossentropy를 사용하거나,  

y_train을 원핫인코딩한 다음 categorical_crossentropy사용


In [33]:
loss_func = tf.keras.losses.sparse_categorical_crossentropy
loss_func

<function tensorflow.python.keras.losses.sparse_categorical_crossentropy>

In [34]:
# y_train이 원핫이코딩이 되어있느면 categorical_crossentropy 사용
tf.keras.losses.categorical_crossentropy

<function tensorflow.python.keras.losses.categorical_crossentropy>

In [36]:
# 이진분류면 binary_crossentropy
tf.keras.losses.binary_crossentropy

<function tensorflow.python.keras.losses.binary_crossentropy>

# Optimizer 설정하기
* sgd : tf.keras.optimizers.SGD()
* rmsprops : tf.keras.optimizers.RMSprop()
* adam : tf.keras.optimizers.Adam() - 일반적으로 제일 많이 사용하는 최적화 기법,
뭘쓸지 모르겠으면 adam 선택

In [37]:
optm = tf.keras.optimizers.Adam()
optm

## 테스트 세트 평가방법 (Metrics)  선정하기
* 테스트 세트의 평가방식(evaluate)

* loss는 훈련딘 데이터의 지표
* test의 평가방식에는 loss를 구한다.
* 훈련되기 위한 내용을 갱신하기 위해 loss를 구함
* 분류문제에서 테스트 평가 방식에는 rmse사용 안함

In [38]:
metrics = ['accuracy']
# metrics = ['acc']
# metrics = ['tf.keras.metrics.Accuracy']

# 모델 컴파일
* 텐서프로우 세션에 위치한 게사 ㄴ그래프에 데이터를 집어넣기 직전 작업을 완료
* 손실함수, 최적화 평가방법을 계산그래프에 적용

In [39]:
model.compile(
    optimizer=optm,
    loss=loss_func,
    metrics=metrics
)

# 훈련용 하이퍼 파라미터 설정
 * 에폭 횟수(num_epochs)
 * 배치크기(batch_size)


In [41]:
num_epochs = 10
batch_size = 32

# 훈련시작
 * fit

In [43]:
model.fit(
    X_train, # feature
    y_train, # target
    batch_size=batch_size, # 배치 사이즈
    epochs=num_epochs, # 에폭 횟수
    shuffle=True, # 데이터를 섞어가면서 훈련
    validation_split=0.2 # 검증 세트 비율
)

Epoch 1/10
1500/1500 [==============================] - 11s 7ms/step - loss: 0.2023 - accuracy: 0.9388 - val_loss: 0.1295 - val_accuracy: 0.9596
Epoch 2/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0831 - accuracy: 0.9742 - val_loss: 0.1131 - val_accuracy: 0.9672
Epoch 3/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0602 - accuracy: 0.9810 - val_loss: 0.0863 - val_accuracy: 0.9726
Epoch 4/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0426 - accuracy: 0.9867 - val_loss: 0.1132 - val_accuracy: 0.9698
Epoch 5/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0356 - accuracy: 0.9887 - val_loss: 0.1164 - val_accuracy: 0.9686
Epoch 6/10
1500/1500 [==============================] - 11s 7ms/step - loss: 0.0276 - accuracy: 0.9913 - val_loss: 0.0961 - val_accuracy: 0.9765
Epoch 7/10
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0269 - accuracy: 0.9915 - val_loss: 0.0859 - val_ac

In [45]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0997 - accuracy: 0.9799


[0.09966485947370529, 0.9799000024795532]

In [1]:
import tensorflow as tf
from tensorflow.keras import datasets

mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


# 필요한 레이어들 불러오기
* Flatten
* Dense
* 레이어들을 순서대로 엮어줄 sequential 모델 가져오기
  * ordersdDict의 역할
* Input 레이어가 굳이 없어도 된다. 단 첫번째 레이어에 입력 데이터의 형상을 지정(input_shape)

In [2]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

Sequential 모델링은 단순하게 파이썬의 리스트에 레이어를 추가시키는 개념

In [3]:
# 모델 안에 리스트 형태로 넣기
model = Sequential([
                    Flatten(input_shape=(28, 28)), # 자동으로 평탄화가 된다.
                    Dense(512, activation='relu'),
                    Dense(252, activation='relu'),
                    Dense(98, activation='relu'),
                    Dense(122, activation='relu'),
                    Dense(32, activation='relu'),
                    Dense(74, activation='relu'),
                    Dense(11, activation='relu'),
                    Dense(10, activation='softmax')
])
# 하나의 모델링을 할 때 사용가능

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dense_1 (Dense)              (None, 252)               129276    
_________________________________________________________________
dense_2 (Dense)              (None, 98)                24794     
_________________________________________________________________
dense_3 (Dense)              (None, 122)               12078     
_________________________________________________________________
dense_4 (Dense)              (None, 32)                3936      
_________________________________________________________________
dense_5 (Dense)              (None, 74)                2

모델 컴파일 

In [7]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['acc']
)


훈련

In [8]:
model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=15,
    batch_size=32
)

Epoch 1/15
1875/1875 [==============================] - 8s 3ms/step - loss: 1.9310 - acc: 0.2601 - val_loss: 1.6604 - val_acc: 0.2879
Epoch 2/15
1875/1875 [==============================] - 5s 3ms/step - loss: 1.5799 - acc: 0.3765 - val_loss: 1.2052 - val_acc: 0.5349
Epoch 3/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.7841 - acc: 0.7574 - val_loss: 0.4084 - val_acc: 0.9244
Epoch 4/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2841 - acc: 0.9459 - val_loss: 0.2329 - val_acc: 0.9506
Epoch 5/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1825 - acc: 0.9601 - val_loss: 0.2291 - val_acc: 0.9538
Epoch 6/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1426 - acc: 0.9677 - val_loss: 0.1472 - val_acc: 0.9699
Epoch 7/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1028 - acc: 0.9753 - val_loss: 0.1549 - val_acc: 0.9632
Epoch 8/15
1875/1875 [==============================] - 5s 3ms

# 실습
* 1층 Flatten 
* Dense(512, relu) - Dense(256-relu) - Dense(10 - softmax)
* y_tain ohe
* y_test ohe
* optimizer - adam
* metrics - acc
* loss

In [1]:
import tensorflow as tf
from tensorflow.keras import datasets

mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [2]:
from tensorflow.keras.layers import Dense, Flatten, 
from tensorflow.keras.models import Sequential

In [3]:
y_train_one_hot = tf.one_hot(y_train, 10)
y_test_one_hot = tf.one_hot(y_test, 10)

In [11]:
model = Sequential([
          Flatten(input_shape=(28, 28)),
          Dense(512, activation='relu'),
          Dense(256, activation='relu'),
          Dense(10, activation='softmax')
          ])
          
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['acc']
)

In [14]:
model.fit(
    X_train,
    y_train_one_hot,
    validation_split=0.2,
    epochs=10,
    batch_size=32
    )

Epoch 1/10
1500/1500 [==============================] - 7s 2ms/step - loss: 1.8243 - acc: 0.8965 - val_loss: 0.2902 - val_acc: 0.9400
Epoch 2/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.2289 - acc: 0.9455 - val_loss: 0.2232 - val_acc: 0.9438
Epoch 3/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.1823 - acc: 0.9530 - val_loss: 0.1856 - val_acc: 0.9546
Epoch 4/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.1468 - acc: 0.9605 - val_loss: 0.2022 - val_acc: 0.9532
Epoch 5/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.1395 - acc: 0.9626 - val_loss: 0.1658 - val_acc: 0.9629
Epoch 6/10
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1332 - acc: 0.9650 - val_loss: 0.1696 - val_acc: 0.9603
Epoch 7/10
1500/1500 [==============================] - 4s 2ms/step - loss: 0.1159 - acc: 0.9694 - val_loss: 0.1689 - val_acc: 0.9608
Epoch 8/10
1500/1500 [==============================] - 4s 2ms