<a href="https://colab.research.google.com/github/nureeee/DeepLearning/blob/main/%EC%86%90%EC%8B%A4%ED%95%A8%EC%88%98%2C_%EB%AF%B8%EB%8B%88%EB%B0%B0%EC%B9%98_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 지표
* 산황 판단을 내리기 위한 기준을 정량화 한 것

## 신경망에서의 지표
**신경망에서는 잘 못맞춘 것**을 지표로 삼는 것을 주로 사용한다
 * 잘못맞춘 것이 낮은 신경망이 좋은 신경망이다.

# 평균 제곱 오차

* cross entropy error는 분류에 MSE는 회귀에 사용한다.

In [1]:
import numpy as np

# 교차 엔트로피 오차 ( Cross Entropy Error )


In [2]:
def criss_entropy_error(y, t):
    delta = le-7 # 0.0000001
    return -np.sum(t * np.log(y + delta)) # 로그에 0 이 들어가면 음수 무한대가 되기 떄문에 아주 작은 값 delta를 넣어준다
    # delta는 셜과에 영향을 미치지 않는다.


# 미니배치 학습

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [4]:
# mnist 데이터 세트 로딩
from tensorflow.keras import datasets
mnist = datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [5]:
TRAIN_IMAGE_SIZE = X_train.shape[0]

X_train = X_train.reshape(TRAIN_IMAGE_SIZE, -1) # x_train shape바꿔주기
X_train.shape, y_train.shape

((60000, 784), (60000,))

# y_train 원핫 인코딩

In [9]:
y_train[:3]
# 원핫 인코딩이 되기 위한 shape으로 만들기(60000,)에서 (-1, 1)로 바꿔서 원핫인코딩이 0과 1로 바뀌기 위해 스칼라 값이 10개가 되기 위해 바꿈
# 항목별로 10개가 필요하기 때문에 

array([5, 0, 4], dtype=uint8)

In [13]:
y_train = y_train.reshape(-1, 1)
y_train.shape

(60000, 1)

In [18]:
y_train[:3]

array([[5],
       [0],
       [4]], dtype=uint8)

In [14]:
# 내가한 코드....
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder() # ohe

# # 원핫 인코딩을 하기 위해 shape을 바꿔준다.
# y_train = y_train.reshape(-1, 1) 

# # 원핫인코딩을 통해 데이터를 변형시켜준다.
y_train_ohe = ohe.fit_transform(y_train)

# # 데이터의 shape을 확인해 준다.
# y_train_ohe.shape

# print(y_train_ohe)

In [16]:
y_train_ohe_arr = y_train_ohe.toarray()
y_train_ohe_arr.shape

(60000, 10)

In [17]:
y_train_ohe_arr[:3]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

# 미니배치 구현

In [20]:
import numpy as np

# 훈련데이터 전체에서 무작위로 10장만 빼오기
train_size = X_train.shape[0] # 전체 훈련 데이터 세트 크기
batch_size = 10 # 미니배치 사이즈

batch_mask = np.random.choice(train_size, batch_size)

batch_mask


array([11869, 10911, 22804, 41590, 23268, 48049, 47038,  2919,  5144,
       45661])

In [21]:
X_batch = X_train[batch_mask]
t_batch = y_train_ohe_arr[batch_mask]

X_batch.shape, t_batch.shape

((10, 784), (10, 10))

## ver 1 - 원핫인코딩이 되어 있는 형태!

In [22]:
def cross_entropy_error_v1(y, t):
    
    delta = 1e-6
    
    if y.ndim == 1: # 배치를 사용하지 않은 경우
        #batch 사이즈를 강제로 1로 저장한다
        t = t.reshape(1, -1)
        y = y.reshape(1, -1)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + delta)) / batch_size

## ver 2 - t가 원핫인코딩이 되어 있지 않으면?

In [25]:
def cross_entropy_error_v2(y, t):
    if y.ndim ==1:
        t = t.reshape(1, t.size) # t.size대신 -1을 넣어도 된다, t의 원소개수
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arrange(batch_size), t])) / batch_size