<a href="https://colab.research.google.com/github/nureeee/DeepLearning/blob/main/%EC%97%AD%EC%A0%84%ED%8C%8C_%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 계층 ( Layer )
* 국소적 계산
 * 내가 관심있는 연산만 신경 쓰는 것
 * **계층**별로 국소적 계산이 일어난다!
 * 하나의 계층은 하나의 일만 (국소적) 전문적으로 할 수 있어야 한다.
* 예를 들어 ReLU 계층을 만들었으면 ReLU에 대한 순전파, 역전파만 신경쓰자!

## 레이어 구현의 주안점
* 순전파와 역전파를 어떻게 구현해야 할지에 대한 계획을 세워야 한다.
 1. 논문을 보고 하는 ㄱ경우
  * 논문에 나와있는 순전파, 역전파 수식을 연구
  * 수식을 효율적, 간편하게 짤 수 맀는지에 대한 연구
  * 조건문, 반복문을 최대한 배제
2. 스스로 비즈니스를 만들어서 하는 경우 
  * 수식을 세우고 컴퓨터로 테스츠를 해 봐여 한다.
  * 컴퓨터에 맞는 수식을 세웠는지 컴퓨터로 검증이 필요하다.

# 1. 곱셉 계층 구현하기
입력이 x, y 일 때
* forward(순전파) : x * y
* backward(역전파) : dx = 미분값 * y, dy = 미분값 * x
* 비고 : forward시에 입력되었던 x, y를 저장하고 있어애 한다. 그래야 backward할 때 반대방향으로 곱해줄 수 잇다,

In [ ]:
import numpy as np

In [ ]:
class MulLayer:
    # 딥러닝 레이어 초기화 (생성자에서)는 레이어 전체에서 사용할 옵션이나 변수를 미리 준비
    def __init__(self):
        # 변수만 만ㄴ들어 놓기
        self.x = None
        self.y = None
        # 여기서 x, y는 클래스 전체에서 사용할 수 있음
        # 뭔가 하기 위한 재료?? 레이어등을 준비를 생성자에서 한다.
        # 모든 준비 과정들 ??
    
    # 곱셈 레이어에서는 역전파에 필요한 변수를 저장
    def forward(self, x, y):
        # 생성자에서 만들어 놓은 변수에 값 넣기
        self.x = x
        self.y = y

        # 순전파 연산
        out = x * y
        return out

    # dout : 다음 층에서 흘러 들어오는 미분ㅅㄱ값
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x

        return dx, dy

곱셈 레이어 테스츠

In [ ]:
# 순전파
# 계층은 2개
apple = 100 # 사과 개당 가격
apple_cnt = 2 # 사과의 개수 
tax = 1.1 # 소비세

# (apple * apple_cnt) * tax

mul_apple_layer = MulLayer() # 사과 전체 가격을 구할 레이어
mul_tax_layer = MulLayer() # 소비세까지 적용시킨 가격을 구할 레이어

# 순전파 수행
# 순서가 굉장히 중요
# 게획한 순서 그대로 레이어를 배치해서 연산을 한다.
# 순서가 다르면 역전파 시에 문제가 발생한다.

# 반드시 순전파의 반대방향으로 계산

apple_price = mul_apple_layer.forward(apple, apple_cnt)
price       = mul_tax_layer.forward(apple_price, tax)

print('최종 사과의 가격 : {:.0f}'.format(price))

최종 사과의 가격 : 220


In [ ]:
# 역전파 수행하기
# 제일 마지막 값에 대한 미분값을 생각하기
# d돈통 / d포스기 = 1
dprice = 1

dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_cnt = mul_apple_layer.backward(dapple_price)

print('사과 전체 가격에 대한 미분값 : {}'.format(dapple_price))
print('사과 1개 가격에 대한 미분값 : {}'.format(dapple))
print('사과 개수에 대한 미분값 : {}'.format(dapple_cnt))
print('소비세 대한 미분값 : {}'.format(dtax))

사과 전체 가격에 대한 미분값 : 1.1
사과 1개 가격에 대한 미분값 : 2.2
사과 개수에 대한 미분값 : 110.00000000000001
소비세 대한 미분값 : 200


# 2. 덧셈 계층 구현하기
* forward : x + y
* backward : 뒷층에서 보낸 미분값에 1만 하면 된다. dx = dout * 1, dy = dout * 1
 * dx = dout * dforward/dx
 * dy = dout * dbackward/dy
* 비고 : 곱셈게층과는 달게 forward시에 입력된 값을 가지고 있지 않아도 된다.

In [ ]:
class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, y):
        out = x + y
        return out
    
    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1

        return dx, dy

In [ ]:
apple = 100
apple_cnt = 2

orange = 150
orange_cnt = 3

tax = 1.1

In [ ]:
# 1.전체 가격
# 2. 사과 개수 미분값
# 3. 사과 전체 가격 미분값
# 4. 사과 1개 가격 미분값

# 5. 오렌지 개수 미분값
# 6. 오렌지 전체 가격 미분값
# 7. 오렌지 1개 가격미분값

# 8. 소비세 미분값

In [ ]:
# 1계층
mul_apple_layer = MulLayer() # 사과전체의 가격의 레이러???
mul_orange_layer = MulLayer() # 오렌지 전체의 가격의 레이어
# 2계층
add_apple_orange_layer = AddLayer() # 오렌지와 사과가격의 합의 레이어??
# 3계층
mul_apple_orange_tax_layer = MulLayer() # 오렌지와 사과의 소비세의 레이어??


# 순전파
# 1계층 게산
apple_price = mul_apple_layer.forward(apple, apple_cnt)
orange_price = mul_orange_layer.forward(orange, orange_cnt)
# 2계층 계산
apple_orange_price = add_apple_orange_layer.forward(apple_price, orange_price)
# 3계층 계산
total_price = mul_apple_orange_tax_layer.forward(apple_orange_price, tax)
print('총 가격 : {}'.format(total_price))

총 가격 : 715.0000000000001


In [ ]:
# 역전파

dtotal_price = 1

dapple_orange_price, dtax = mul_apple_orange_tax_layer.backward(dtotal_price)
dapple_price, dorange_price = add_apple_orange_layer.backward(dapple_orange_price)
dorange, dorange_cnt = mul_orange_layer.backward(dorange_price)
dapple, dapple_cnt = mul_apple_layer.backward(dapple_price)

print(total_price) # 전체 가격
print('\n')
print(dapple_cnt) # 사과 개수 미분
print(dapple_price) # 사과 전체 가격 미분
print(dapple) # 사과 1개 가격 미분
print('\n')
print(dorange_cnt) # 오렌지 개수 미분
print(dorange_price) # 오렌지 전체 가격 미분
print(dorange) # 오렌지 1개 가격 미분
print('\n')
print(dtax) # 소비세 미분 가격

715.0000000000001


110.00000000000001
1.1
2.2


165.0
1.1
3.3000000000000003


650


# 신경망 레이어 구현

## ReLU 레이어
* forward : 입력값이 0보다 크면 입력값을 그대로 출력
* backward : forward 시에 0보다 작았으면 해당값 위치에 0, 0보다 크면 변화율이1

In [ ]:
class ReLU:
    def __init__(self):

        # mask : 순전파 시에 음수였던 인덱스를 저장하기 위함
        # mask가 있어야 순전파 때 음수였던 부분을 역전파 때 0으로 만들어 줄 수 있다.
        self.mask = None

    def forward(self, x):
        self.mask = (x <= 0) # 음수면 True, 양수면 False

        out = x.copy() # 원본 배열 복사
        out[self.mask] = 0 # 음수 엮전 부분만 0이된다

        return out

    def backward(self, dout):
        # 순전파 때 음수였던 부분을 0으러 만들었다.
        dout[self.mask] = 0
        dx = dout 

        return dx

In [ ]:
x = np.array([[1.0, -0.5],
             [-2.0, 3.0]])
relu = ReLU()
relu.forward(x)


array([[1., 0.],
       [0., 3.]])

In [ ]:
relu.mask

array([[False,  True],
       [ True, False]])

In [ ]:
dout = np.array([[-0.1, 3.0],
            [1.3, -1.1]])
relu.backward(dout)

array([[-0.1,  0. ],
       [ 0. , -1.1]])

* 시그모이드 레이어에서 순전파 때 기억라고 있어야 할 값 : y값만 알고 있으면 된다.

In [ ]:
class Sigmoid:

    def __init__(self):
        # y를 out이라고 하자
        self.out = None

    def forward(self, x):
        out = 1 / ( 1 + np.exp(-x))
        self.out = out

        return out

    def backward(self, dout):
        dx = dout * self.out * ( 1 - self.out)
        return dx

## Affine 계층
* forward : 입력된 x 데이터에 대해 평탄화 수행 wx+b 출력
 1. WX + B
 2. 평탄화
   * 1차원 배열로 데이터가 들어왔을 때 대응
   * 다차원 배열 ( 텐서 )에 대한 대응
   *  **원본 데이터의 형상을 저장**
   >미분값은 2차원배열로만 나오기ㅣ때문에 원본의 shape으로 나타내기 위해 결과값을 reshape을 해준다

* backward
 1. 미분값(dout)과 가중치의 전치행렬 내적
 2. 입력값의 전치행렬과 미분값 내적(가중치에 대한 내적)
 3. 배치를 축으로 편향 합 구하기 (axis=0)
 4. 입력값의 미분값의 형상을 원본데이터의 형상으로 다시 바꿔주기
 

In [ ]:
class Affine:

    def _init__(self, w, b):
        # 1. 가중치, 편향, 입력값 x
        # 실행할 때 w, b는 입력이 되어있어야 한다.
        self.w = w
        self.b = b

        self.x = None

        # 2. x의 형상 저장
        # x에 대한 역전파를 수행할 때 모양이 바뀌어 버린 x의 미분값의 
        # 형상을 원래대로 돌려놓기 위해 원본 x의 형상을 저장한 변수
        self.original_x_shape = None
        
        # 3. w, b의 기울기 배열
        # 최적화를 위해 각 매개변수의 미분값을 가지고 있어야 한다
        # 추후에 경사하강법 등을 구현하기 위해 사용
        # dw, db를 사용해서 w, b를 갱신 하는 것을 <<학습>>이라고 한다
        self.dw = None
        self.db = None

    def forward(self, x):
        # 텐서 대응을 위해 입력값 x의 형상을 저장한다.
        self.original_x_shape = x.shape

        # 평탄화 진행
        DATA_SIZE = x.shape[0]
        x = x.reshape(DATA_SIZE, -1)

        self.x = x  # 역전파 떄 가중치와 내적을 하기 위해 저장
        
        out = np.dot(self.x, self, w) + self.b

        return out
        # 활성화 계층을 따로 만들어 주었기 때문에 따로 넣어주지 않아도 된다.

    def backward(self, dout):
        dx = np.dot(dout, self.w.T)

        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)

        dx = dx.reshape(*self.original_x_shape) # *이 들어가면 언팩킹되어 순서되로 들어간다.

        return dx


## 소프트 맥스 with 로스 계층 (출력층)
* 소프트맥스에 의한 분류 밑 CEE를 활용한 손실함수를 동시에 구현
* forward
  * 순전파 시에는 소프트맥스를 적용하고 로스를 적용
  


In [ ]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 
    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    # 훈련 데이터가 원-핫 벡터라면 정답 레이블의 인덱스로 반환
    if t.size == y.size:
        t = t.argmax(axis=1)
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [ ]:
class SoftmaxWithLoss:

    def __init__(self):
        self.loss = None # 손실값 함수에 대한 미분값을 구할 것이기 때문에 값보다는 함수가 중요??
        self.y = None # 예측값 (역전파 때 사용)
        self.t = None # 정답 레이블 (역전파 때 사용)

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)

        return self.loss

    def backward(self, dout=1): # dout이 1인 이유는돈통과 포스기를 생각하자

        #배치 고려하기
        batch_size = self.t.shape[0]
        
        # t가 원핫인코딩이 되어있는지, 안되어 있는지 고려
        if self.t.size == self.y.size: # 출력층의 원소 개수를 비교하는 것은 원핫인코딩이 되어있는 t
        # 항상 y는 softmax의 결과물(N, output_size) > 출력층 개수
        # t가 원핫인코딩이 되어있으면 (N, output_size)
        # t가 원핫인코딩이 안되어 있으면(N,)
            dx = (self.y - self.t) / batch_size
        else: #t가 원핫인코딩이 되어있지 않은 경우
            dx = self.y.copy()

        # 원핫인코딩이 되어있지 않은 t는 정답 레이블의 인덱스로 생각할 수 있다.
        # y = [0.2, 0.1, 0.7], t = 2
            dx[np.arange(batch_size), self.t] -= 1
            dx = dx / batch_size

        return dx


# 신경망 레이어를 이용해서 MNIST 분류 네트워크 구축

In [ ]:
from collections import OrderedDict # 추가 순서가 유지되는 dict

In [ ]:
class TwoLayerNet:

    def __init__(self, input_size, hidden_size, output_size, weight-std=0.01):
        # 매개변수 초기화
        self.params = {}

        # 1층 은닉층을 위한 매개변수
        self.params['w1'] = weight_init_std 8 np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)

        #2층 출력층을 위한 매개변수
        self.params['w2'] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output)

        # 레이어 만들기
        # 추가되는 레이어의 순서가 바뀌면 안되기 때문에 OrdereDict를 활용
        self.layers = OrderedDict()

        # Affine 1층 (은닉층 - Fully Connected Layer)
        self.layers['Affine1'] = Affine(self.params['w1'], self.params['b1'])
        self.layers['ReLU'] = RelU()

        # Affine 층 (출력층)
        self.layers['Affine2'] = Affine(self.params['w2'], self.params['b2'])

        # 항상 마지막 층은 소프트맥스위드로스가 되어야 한다.
        self.lastLayer = SoftmaxWithLoss()

    def predict(self, x):
        for layer in self.layers.values(): # value들의 리스트
            x = layer.forward(x)

        return x

    def loss(self, x, t):
        y = self.predict(x)
        
        return self.lastLayer.forward(y, t)     
    
    def gradient(self, x, t):

        self.loss(x, t) # 역전파를 하기 위해 순전파의 값을 자기고 해야된다.
        
        dout = 1
        dout = self.lastLayer.backward(dout) 

        grads = {}
        grad['w1']

        return grads
